import json
from typing import Any

import numpy as np
import pandas as pd

from utils.ai import build_pandas_query_prompt, call_gemini_api, extract_code_from_gemini_response
from utils.db import get_dataset


def build_column_schema_string(df: pd.DataFrame) -> str:
    return "\n".join([f"{col}: {dtype}" for col, dtype in df.dtypes.astype(str).items()])


def execute_pandas_code(code: str, df: pd.DataFrame) -> tuple[Any | None, str | None]:
    if not code or not code.strip():
        return None, "No pandas code was generated by Gemini."

    safe_builtins = {
        "abs": abs,
        "all": all,
        "any": any,
        "bool": bool,
        "dict": dict,
        "float": float,
        "int": int,
        "len": len,
        "list": list,
        "max": max,
        "min": min,
        "pow": pow,
        "range": range,
        "round": round,
        "set": set,
        "sorted": sorted,
        "str": str,
        "sum": sum,
        "tuple": tuple,
        "zip": zip,
    }

    globals_obj = {"df": df, "pd": pd, "__builtins__": safe_builtins}
    local_vars: dict[str, Any] = {}

    try:
        exec(code, globals_obj, local_vars)
    except Exception as exc:
        return None, f"Execution error: {exc}"

    output = local_vars.get("result")
    if output is None:
        output = local_vars.get("df")

    if output is None:
        return None, "The generated code did not assign a DataFrame or Series to `result` or `df`."

    return output, None


def serialize_query_output(value: Any) -> Any:
    if isinstance(value, pd.DataFrame):
        return {
            "type": "dataframe",
            "columns": value.columns.tolist(),
            "shape": list(value.shape),
            "records": json.loads(value.to_json(date_format="iso", orient="records")),
        }

    if isinstance(value, pd.Series):
        return {
            "type": "series",
            "name": value.name,
            "dtype": str(value.dtype),
            "values": json.loads(value.to_json(date_format="iso")),
        }

    if isinstance(value, (np.integer, np.floating, np.bool_)):
        return value.item()

    if isinstance(value, (str, int, float, bool)) or value is None:
        return value

    if isinstance(value, dict):
        return {str(key): serialize_query_output(val) for key, val in value.items()}

    if isinstance(value, (list, tuple)):
        return [serialize_query_output(item) for item in value]

    try:
        return str(value)
    except Exception:
        return None


def generate_pandas_code(question: str, schema: dict[str, str]) -> dict:
    schema_text = "\n".join([f"{column}: {data_type}" for column, data_type in schema.items()])
    prompt = build_pandas_query_prompt(question, schema_text)
    response_text = call_gemini_api(prompt)
    pandas_code = extract_code_from_gemini_response(response_text)

    return {
        "prompt": prompt,
        "pandas_code": pandas_code,
    }


def query_dataset(dataset_id: str, question: str) -> dict:
    df = get_dataset(dataset_id)
    schema_text = build_column_schema_string(df)

    prompt = build_pandas_query_prompt(question, schema_text)
    response_text = call_gemini_api(prompt)
    pandas_code = extract_code_from_gemini_response(response_text)

    output, error = execute_pandas_code(pandas_code, df)
    serialized_result = None if output is None else serialize_query_output(output)

    return {
        "prompt": prompt,
        "pandas_code": pandas_code,
        "result": serialized_result,
        "error": error,
    }
